import { ArrowRight, Mic2, Sparkles, Upload } from 'lucide-react';
import { request } from '../lib/api';
import { useState } from 'react';

export default function ArtistStudioPage({ tracks, onNotice, onUploaded }) {
  const [title, setTitle] = useState(''); const [file, setFile] = useState(null); const [loading, setLoading] = useState(false);
  async function upload(event) { event.preventDefault(); if (!file || !title.trim()) return onNotice('Add a title and audio file first'); if (file.size > 50 * 1024 * 1024) return onNotice('Audio file must be 50MB or smaller'); const body = new FormData(); body.append('title', title.trim()); body.append('music', file); setLoading(true); try { await request('/music/upload', { method: 'POST', body }); setTitle(''); setFile(null); event.target.reset(); await onUploaded?.(); onNotice('Track uploaded successfully. It is now visible to listeners.'); } catch (error) { onNotice(error.message); } finally { setLoading(false); } }
  return <section className="studio page-enter"><div className="welcome-row"><div><p className="eyebrow">Artist workspace</p><h2>Make some <em>noise.</em></h2></div><span className="artist-badge"><Mic2 size={15} /> Artist account</span></div><div className="studio-grid"><form className="upload-panel" onSubmit={upload}><div className="panel-heading"><span className="panel-icon"><Upload size={18} /></span><div><h3>Release a track</h3><p>Share something new with your listeners.</p></div></div><label>Track title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Midnight Drive" /></label><label className="file-drop"><input type="file" accept="audio/*" onChange={(event) => setFile(event.target.files?.[0] || null)} /><Upload size={25} /><b>{file ? file.name : 'Drop your audio here'}</b><span>{file ? 'Ready to upload' : 'MP3, WAV or M4A · 50MB max'}</span></label><button className="button button-green full-button" disabled={loading}>{loading ? 'Uploading…' : 'Publish track'} <ArrowRight size={16} /></button></form><div className="studio-side"><div className="stat-panel"><p className="eyebrow">Your catalog</p><strong>{tracks.length.toString().padStart(2, '0')}</strong><span>published tracks</span><div className="sparkline"><i /><i /><i /><i /><i /><i /><i /><i /><i /></div></div><div className="tip-panel"><Sparkles size={18} /><b>Small ritual, big reach</b><p>Artists with a consistent release rhythm grow their audience 3× faster.</p></div></div></div></section>;
}
