import { useState } from 'react';
import { ArrowRight, Disc3, Headphones, Mic2, X } from 'lucide-react';
import { request } from '../lib/api';

export default function AuthModal({ mode, onClose, onAuth }) {
  const [isLogin, setIsLogin] = useState(mode === 'login'); const [role, setRole] = useState('user'); const [form, setForm] = useState({ username: '', email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { const payload = isLogin ? { username: form.username.trim(), password: form.password } : { username: form.username.trim(), email: form.email.trim(), password: form.password, role }; const data = await request(`/auth/${isLogin ? 'login' : 'register'}`, { method: 'POST', body: JSON.stringify(payload) }); onAuth(data); } catch (requestError) { setError(requestError.message === 'Failed to fetch' ? 'Cannot reach the API. Check that the frontend is using http://localhost:3000.' : requestError.message); } finally { setLoading(false); } }
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="auth-modal"><button type="button" className="modal-close" onClick={onClose} aria-label="Close"><X size={18} /></button><div className="auth-mark"><Disc3 size={20} /></div><p className="eyebrow">Welcome to sonora</p><h2>{isLogin ? 'Good to hear you.' : 'Find your frequency.'}</h2><p className="modal-copy">{isLogin ? 'Pick up exactly where you left off.' : 'Create a home for the music that matters.'}</p><form onSubmit={submit}>{!isLogin && <><div className="role-switch"><button type="button" className={role === 'user' ? 'selected' : ''} onClick={() => setRole('user')}><Headphones size={15} /> Listener</button><button type="button" className={role === 'artist' ? 'selected' : ''} onClick={() => setRole('artist')}><Mic2 size={15} /> Artist</button></div><label>Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="you@example.com" /></label></>}<label>{isLogin ? 'Username or email' : 'Username'}<input required type={isLogin ? 'text' : 'text'} value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} placeholder={isLogin ? 'you@example.com or username' : 'Your stage name'} /></label><label>Password<input required type="password" minLength="6" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="At least 6 characters" /></label>{error && <p className="form-error">{error}</p>}<button type="submit" className="button button-green full-button" disabled={loading}>{loading ? 'One moment…' : isLogin ? 'Enter Sonora' : 'Create account'} <ArrowRight size={16} /></button></form><p className="auth-switch">{isLogin ? 'New to Sonora?' : 'Already have an account?'} <button type="button" onClick={() => { setIsLogin(!isLogin); setError(''); }}> {isLogin ? 'Create one' : 'Log in'}</button></p></div></div>;
}
