import { ArrowRight, Disc3, Heart, Play, UserRound } from 'lucide-react';

const covers = [
  'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
  'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=600&q=80',
  'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80',
  'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=600&q=80'
];

export default function DashboardPage({ user, page, tracks, albums, onNavigate, onPlay }) {
  const sampleTracks = tracks.length ? tracks : [{ title: 'Golden Hour', artist: { username: 'Juno Parks' } }, { title: 'Slow Motion', artist: { username: 'Maya Sol' } }, { title: 'Northbound', artist: { username: 'The Coastline' } }];
  const albumItems = albums.length ? albums : ['Late night / early morning', 'A little bit of sunshine', 'The art of letting go', 'Headphones on'];
  return <section className="dashboard page-enter"><div className="welcome-row"><div><p className="eyebrow">{page === 'library' ? 'Your collection' : 'Saturday, September 19'}</p><h2>{page === 'library' ? 'Made for your ears.' : <>Good morning, <em>{user.username}.</em></>}</h2></div><button type="button" className="round-button" aria-label="Your profile"><UserRound size={18} /></button></div><div className="feature-band"><div><span className="pill">SONORA SELECTS · 09</span><h3>Soft edges,<br /><em>sharp feelings.</em></h3><p>New releases for slow starts and wide-open windows.</p><button type="button" className="button button-light" onClick={() => onPlay(sampleTracks[0])}>Play selection <Play size={15} fill="currentColor" /></button></div><div className="band-art"><img src={covers[0]} alt="Abstract concert crowd" /><span className="vinyl"><Disc3 size={44} /></span></div></div><section className="content-section"><div className="section-heading"><div><p className="eyebrow">{albums.length ? 'Fresh from the studio' : 'Handpicked for you'}</p><h3>{albums.length ? 'Latest albums' : 'Made for your mood'}</h3></div><button type="button" className="link-button" onClick={() => onNavigate('library')}>See all <ArrowRight size={15} /></button></div><div className="album-grid">{albumItems.slice(0, 4).map((album, index) => <div className="album-card" key={album._id || album.title || album}><div className="album-cover"><img src={covers[index]} alt="" /><button type="button" className="play-float" aria-label={`Play ${album.title || album}`} onClick={() => onPlay(album)}><Play size={15} fill="currentColor" /></button></div><b>{album.title || album}</b><span>{album.artist?.username || 'Sonora editorial'}</span></div>)}</div></section><section className="content-section track-section"><div className="section-heading"><div><p className="eyebrow">The pulse right now</p><h3>Trending tracks</h3></div><span className="live-label"><i /> Updated today</span></div><div className="track-list">{sampleTracks.slice(0, 4).map((track, index) => <div className="track-row" key={track._id || index}><span className="track-number">0{index + 1}</span><div className="track-art"><img src={covers[(index + 1) % covers.length]} alt="" /></div><div className="track-info"><b>{track.title}</b><span>{track.artist?.username || 'Sonora artist'}</span></div><span className="track-time">{3 + index}:{index ? '2' : '48'}</span><button type="button" className="heart-button" aria-label="Add to favorites"><Heart size={16} /></button><button type="button" className="row-play" aria-label={`Play ${track.title}`} onClick={() => onPlay(track)}><Play size={13} fill="currentColor" /></button></div>)}</div></section></section>;
}
